Damping implementation
EPIC-model/epic pull request #549
Opened 2024-01-09 09:59 UTC by sjboeing

Work in progress

2024-01-09 10:09 UTC, sjboeing commented on src/3d/utils/options.f90
> +
Added the prefix damping here. Is this OK?

2024-01-09 10:10 UTC, sjboeing commented on examples/moist.config
> + output%parcel_freq        = 200             ![s] write after these many seconds to the parcel NetCDF file
May revert this in PR, although in practice this is the setting I tend to use in order to limit parcel output.

2024-01-09 12:44 UTC, matt-frey commented on examples/moist.config
> + output%parcel_freq        = 200             ![s] write after these many seconds to the parcel NetCDF file
I usually just turn off parcel dumping completely. `output%write_parcels = .false.`

2024-01-09 12:46 UTC, matt-frey commented on src/3d/utils/options.f90
> +
Yes, that is fine. Otherwise, we can also create a subgroup.

2024-01-10 15:47 UTC, matt-frey requested changes
Looks generally good. However, I suggest some changes. Also, could you change to 4 white space characters instead of 2 as we use 4 throughout EPIC? Thanks.

2024-01-10 15:47 UTC, matt-frey commented on src/3d/parcels/parcel_damping.f90
> +                      enddo
Is this loop really needed? Can't you just write `time_fact = 1.0- dexp(-vorticity_prefactor * strain_mag(ks:ks+1 js:js+1, is:is+1)*dt)`?

2024-01-10 15:47 UTC, matt-frey commented on src/3d/stepper/rk_utils.f90
> +                        strain(3, 3) = -(velgradg(iz, iy, ix, I_DUDX) + velgradg(iz, iy, ix, I_DVDY)) ! S33
This is the same code which we use for the time step estimate. We should put this into a function instead of duplicating the code.

2024-01-10 15:47 UTC, matt-frey commented on src/3d/parcels/parcel_damping.f90
> +                      enddo
Can you maybe also add an explanation to the module how this is done? I.e. the reasoning behind these equations.

2024-01-10 15:51 UTC, sjboeing commented on src/3d/stepper/rk_utils.f90
> +                        strain(3, 3) = -(velgradg(iz, iy, ix, I_DUDX) + velgradg(iz, iy, ix, I_DVDY)) ! S33
Largely, yes. Though the output into an array is different. May try to pack it into a function.

2024-01-10 15:52 UTC, sjboeing commented on src/3d/parcels/parcel_damping.f90
> +                      enddo
I think initially this did not work for me, but maybe something changed in the meantime.

2024-01-10 15:53 UTC, sjboeing commented on src/3d/parcels/parcel_damping.f90
> +                      enddo
I have revised the formulation a couple of times. A draft write-up is section 1 here: https://www.overleaf.com/project/6381d70192a0f271ee433739

2024-01-11 14:15 UTC, matt-frey requested changes
Looks much better now! Thanks! I still have some suggestions. Can you maybe also use spaces between opertions, like a = b + c instead of a=b+c. It helps to improve readability. We usually also add spaces for if-statements, i.e. "if (...)" instead of "if(...)".

2024-01-11 14:15 UTC, matt-frey commented on src/3d/parcels/parcel_damping.f90
> +        subroutine perturbation_damping(dt,l_vorticity,l_scalars,&
Since the information of the `damping` type is globally known, you do not need to pass these.

2024-01-11 14:15 UTC, matt-frey commented on src/3d/parcels/parcel_damping.f90
> +                points = get_ellipsoid_points(parcels%position(:, n), &
Is it safe to have `l_reuse = .true.`?

2024-01-11 14:15 UTC, matt-frey commented on src/3d/parcels/parcel_damping.f90
> +                    weight = point_weight_p2g * weights
Why not assigning to `weights` so you do not need an additional variable `weight`?

2024-01-11 14:16 UTC, matt-frey commented on src/3d/parcels/parcel_damping.f90
> +                      enddo
It may still be good to have at least some explanatory words in the module description. Of course, you do not need to derive the theory there.

2024-01-11 15:50 UTC, sjboeing commented on src/3d/parcels/parcel_damping.f90
> +                    weight = point_weight_p2g * weights
Mainly to alert people these are no longer the weights as they came out of trilinear. Let me know if this is OK.

2024-01-15 17:09 UTC, sjboeing commented
@matt-frey: Let me know if the layout etc. looks OK now.

2024-01-16 08:03 UTC, matt-frey commented on src/3d/parcels/parcel_damping.f90
> +                      enddo
Thanks for adding more info to the module description.

2024-01-16 08:14 UTC, matt-frey reviewed
It looks generally good now. Thanks for the hard work. There are a few places where you could do some code alignment though. I also have a question regarding the calculation of the strain magnitude.

2024-01-16 08:14 UTC, matt-frey commented on src/3d/stepper/rk_utils.f90
> +                        strain_mag(iz, iy, ix) = sqrt(two * strain(1, 1) * strain(1, 1) +&
Why is there a two?

2024-01-16 08:14 UTC, matt-frey commented on src/3d/stepper/rk_utils.f90
> +            strain(2, 2) = velgradgp(I_DVDY)                                   ! S22
You may do some more alignment like here the comment `!S22` is not aligned with the others. Also `!S11`.

2024-01-16 08:14 UTC, matt-frey commented on src/3d/parcels/parcel_damping.f90
> +            logical, intent(in)   :: l_reuse
Alignment.

2024-01-16 08:14 UTC, matt-frey commented on src/3d/stepper/rk_utils.f90
> +                                                        strain(3, 3) * strain(3, 3))
Align with `strain(1, 1)`.

2024-01-16 08:46 UTC, sjboeing commented on src/3d/stepper/rk_utils.f90
> +                        strain_mag(iz, iy, ix) = sqrt(two * strain(1, 1) * strain(1, 1) +&
This is the way the magnitude is defined for Smagorinsky-Lilly, e.g.:
https://en.wikipedia.org/wiki/Large_eddy_simulation#Smagorinsky%E2%80%93Lilly_model

2024-01-16 08:51 UTC, matt-frey commented on src/3d/stepper/rk_utils.f90
> +                        strain_mag(iz, iy, ix) = sqrt(two * strain(1, 1) * strain(1, 1) +&
But shouldn't other components have this prefactor as well?

2024-01-16 09:26 UTC, matt-frey commented on src/3d/stepper/rk_utils.f90
> +                        strain_mag(iz, iy, ix) = sqrt(two * strain(1, 1) * strain(1, 1) +&
Thanks for fixing.

2024-01-16 09:27 UTC, matt-frey approved these changes
Looks good to me now.

2024-01-18 16:26 UTC, merged