Gridded strain
EPIC-model/epic pull request #553
Opened 2024-02-14 14:23 UTC by sjboeing

This branch uses only gridded strain field to deform parcels. Changes to save B33 and use matrix exponentiation not yet included.

2024-02-15 11:21 UTC, matt-frey requested changes

2024-02-15 11:21 UTC, matt-frey commented on src/3d/fields/fields.f90
> +                        , I_DVDX = 4 & ! index for dv/dy strain component
Comment should be `dv/dx`.

2024-02-15 11:21 UTC, matt-frey commented on src/3d/fields/fields.f90
> +                        , I_DVDZ = 6 & ! index for dv/dy strain component
Comment should be `dv/dz`.

2024-02-15 15:59 UTC, matt-frey reviewed
Have you tested this version? (e.g. Beltrami)

2024-02-15 16:49 UTC, sjboeing commented
I have so far run Beltrami, unit tests, and the moist bubble. Just posted some Beltrami results in the slack.

2024-02-16 10:19 UTC, sjboeing commented on src/3d/inversion/inversion.f90
> +            !$omp parallel workshare
@matt-frey: should the halo fill be later? Should it be a halo swap instead?

2024-02-16 10:21 UTC, sjboeing commented on src/3d/inversion/inversion.f90
> +            !$omp parallel workshare
Ah, it should be a fill but placement may be important!

2024-02-16 10:26 UTC, matt-frey commented on src/3d/inversion/inversion.f90
> +            !$omp parallel workshare
It should be a halo fill. Halo swap is actually an accumulation. It is a bit of a misnomer.

2024-02-16 10:29 UTC, matt-frey commented on src/3d/inversion/inversion.f90
> +            !$omp parallel workshare
As you use the vorticity there, it must have the halo being filled properly. I would check the code if this is the case.

2024-02-16 10:33 UTC, matt-frey commented on src/3d/inversion/inversion.f90
> +            !$omp parallel workshare
It should actually not matter if you fill the halo of `velgradg` before or after -- as it overwrites data; but since you see a difference, I could imagine that the vorticity does not have the halo properly filled.

2024-02-16 10:38 UTC, matt-frey commented on src/3d/inversion/inversion.f90
> +            !$omp parallel workshare
Here we alter the vorticity array, but without the halo being updated as it is not needed. https://github.com/EPIC-model/epic/blob/b3fadd22c09e2a583cbdfa5dd49c89420bf58871/src/3d/inversion/inversion.f90#L92C22-L92C44

2024-02-19 09:38 UTC, matt-frey approved these changes
Looks good to me.

@matt-frey This must be implemented in the surface parcel model branch as well.

2024-02-19 09:44 UTC, merged