Implement fixed time step
EPIC-model/epic pull request #572
Opened 2024-07-26 08:21 UTC by sjboeing

2024-08-01 13:47 UTC, matt-frey requested changes

2024-08-01 13:47 UTC, matt-frey commented on src/3d/stepper/rk_utils.f90
> +                dt = time%fixed_dt
I would put this further up in the function and do an early exit. This saves some computation which is anyway discarded in this mode.

2024-08-01 15:59 UTC, sjboeing commented on src/3d/stepper/rk_utils.f90
> +                dt = time%fixed_dt
I was thinking that having the statistics on gmax and bmax could still be useful (for example, in verbose mode), especially since we aim to only use fixed_dt for testing purposes.

2024-08-01 16:17 UTC, matt-frey commented on src/3d/stepper/rk_utils.f90
> +                dt = time%fixed_dt
OK. However, in non-verbose mode nothing is printed. I therefore suggest to do an early extit in non-verbose mode.

2024-08-02 11:52 UTC, sjboeing commented on src/3d/stepper/rk_utils.f90
> +                dt = time%fixed_dt
Should be fixed now. Have a look to see if you like this (it adds a bit more code).

2024-08-02 11:57 UTC, matt-frey approved these changes
Yes, that is expected. Thanks.

2024-08-02 12:07 UTC, merged